ARG ARCH='amd64'
FROM ${ARCH}/debian
ENV CROSS_TRIPLE=${ARCH}
RUN apt update && apt -y install cmake gcc libcurl4-openssl-dev libssl-dev pkg-config zlib1g-dev

WORKDIR /nativebinaries
COPY . /nativebinaries/

CMD ["/bin/bash", "-c", "./build.libgit2.sh"]